/*
###########################################################################################################################################################
															CRIAÇÃO DA TABELA CADPAIS
###########################################################################################################################################################
*/


CREATE TABLE CADPAIS (
    CODIGOPAIS NUMBER(3) NOT NULL,
    DDI VARCHAR2(4) NOT NULL,
    ISO VARCHAR2(2) NOT NULL,
    ISO3 VARCHAR2(3) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    NOMEFORMAL VARCHAR2(100) NOT NULL,
    
    CONSTRAINT PK_CADPAIS PRIMARY KEY (CODIGOPAIS),
    CONSTRAINT UN_CADPAIS_ISO UNIQUE(ISO,ISO3),
    CONSTRAINT UN_CADPAIS_NOME UNIQUE(NOME,NOMEFORMAL)
);

/* COMENTÁRIOS DE TABELAS E COLUNAS*/

COMMENT ON TABLE CADPAIS IS 'TABELA DESTINADA AO CADASTRO DE PAISES';
COMMENT ON COLUMN CADPAIS.CODIGOPAIS IS 'CODIGO INTERNACIONAL DO PAÍS (PRIMARY KEY)';
COMMENT ON COLUMN CADPAIS.ISO IS 'SIGLA EM 2 LETRAS DE CADA PAÍS';
COMMENT ON COLUMN CADPAIS.ISO3 IS 'SIGLA EM 3 LETRAS DE CADA PAÍS';
COMMENT ON COLUMN CADPAIS.NOME IS 'NOME POPULAR DO PAÍS';
COMMENT ON COLUMN CADPAIS.NOMEFORMAL IS 'NOME FORMAL DO PAÍS';

/* INSERÇÃO DOS DADOS FIXOS NA TABELA CADPAIS */

INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (004, 0093, 'AF', 'AFG', 'Afeganistão', 'República Islâmica do Afeganistão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (008, 0355, 'AL', 'ALB', 'Albânia', 'República da Albânia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (012, 0213, 'DZ', 'DZA', 'Algéria', 'República Democrática Popular da Algéria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (016, 1684, 'AS', 'ASM', 'Samoa Americana', 'Território de Samoa Americana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (020, 0376, 'AD', 'AND', 'Andorra', 'Principado Andorra');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (024, 0244, 'AO', 'AGO', 'Angola', 'República de Angola');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (660, 1264, 'AI', 'AIA', 'Anguilla', 'Anguilla');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (010, 0672, 'AQ', 'ATA', 'Antártida', 'Antártida');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (028, 1268, 'AG', 'ATG', 'Antigua e Barbuda', 'Antigua e Barbuda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (032, 0054, 'AR', 'ARG', 'Argentina', 'República Argentina');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (051, 0374, 'AM', 'ARM', 'Armênia', 'República da Armênia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (533, 0297, 'AW', 'ABW', 'Aruba', 'Aruba');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (036, 0061, 'AU', 'AUS', 'Austrália', 'Comunidade da Austrália');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (040, 0043, 'AT', 'AUT', 'Áustria', 'República da Áustria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (031, 0994, 'AZ', 'AZE', 'Azerbaijão', 'República do Azerbaijão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (044, 1242, 'BS', 'BHS', 'Bahamas', 'Comunidade de Bahamas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (048, 0973, 'BH', 'BHR', 'Bahrein', 'Reino do Bahrein');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (050, 0880, 'BD', 'BGD', 'Bangladesh', 'República Popular de Bangladesh');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (052, 0246, 'BB', 'BRB', 'Barbados', 'Barbados');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (112, 0375, 'BY', 'BLR', 'Bielorrússia', 'República da Bielorrússia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (056, 0032, 'BE', 'BEL', 'Bélgica', 'Reino da Bélgica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (084, 0501, 'BZ', 'BLZ', 'Belize', 'Belize');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (204, 0229, 'BJ', 'BEN', 'Benin', 'República do Benin');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (060, 1441, 'BM', 'BMU', 'Bermuda', 'Bermuda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (064, 0975, 'BT', 'BTN', 'Butão', 'Reino do Butão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (068, 0591, 'BO', 'BOL', 'Bolívia', 'Estado Plurinacional da Bolívia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (070, 0387, 'BA', 'BIH', 'Bósnia e Herzegovina', 'Bósnia e Herzegovina');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (072, 0267, 'BW', 'BWA', 'Botswana', 'República da Botswana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (074, 0047, 'BV', 'BVT', 'Ilha Bouvet', 'Ilha Bouvet');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (076, 0055, 'BR', 'BRA', 'Brasil', 'República Federativa do Brasil');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (086, 0246, 'IO', 'IOT', 'Território Britânico do Oceano Índico', 'Território Britânico do Oceano Índico');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (096, 0673, 'BN', 'BRN', 'Brunei', 'Estado do Brunei Darussalam');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (100, 0359, 'BG', 'BGR', 'Bulgária', 'República da Bulgária');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (854, 0226, 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (108, 0257, 'BI', 'BDI', 'Burundi', 'República do Burundi');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (116, 0855, 'KH', 'KHM', 'Camboja', 'Reino do Camboja');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (120, 0237, 'CM', 'CMR', 'Camarões', 'República de Camarões');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (124, 0001, 'CA', 'CAN', 'Canadá', 'Canadá');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (132, 0238, 'CV', 'CPV', 'Cabo Verde', 'República do Cabo Verde');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (136, 1345, 'KY', 'CYM', 'Ilhas Cayman', 'Ilhas Cayman');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (140, 0236, 'CF', 'CAF', 'República Centro-Africana', 'República Centro-Africana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (148, 0235, 'TD', 'TCD', 'Chade', 'República do Chade');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (152, 0056, 'CL', 'CHL', 'Chile', 'República do Chile');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (156, 0086, 'CN', 'CHN', 'China', 'República Popular da China');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (162, 0061, 'CX', 'CXR', 'Ilha Christmas', 'Território da Ilha Christmas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (166, 0672, 'CC', 'CCK', 'Ilhas Cocos (Keeling)', 'Território das Ilhas Cocos (Keeling)');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (170, 0057, 'CO', 'COL', 'Colômbia', 'República da Colômbia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (174, 0269, 'KM', 'COM', 'Comores', 'União das Comores');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (178, 0242, 'CG', 'COG', 'Congo', 'República do Congo');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (180, 0242, 'CD', 'COD', 'Congo (DR)', 'República Democrática do Congo');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (184, 0682, 'CK', 'COK', 'Ilhas Cook', 'Ilhas Cook');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (188, 0506, 'CR', 'CRI', 'Costa Rica', 'República da Costa Rica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (384, 0225, 'CI', 'CIV', 'Costa do Marfim', 'República da Costa do Marfim');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (191, 0385, 'HR', 'HRV', 'Croácia', 'República da Croácia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (192, 0053, 'CU', 'CUB', 'Cuba', 'República de Cuba');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (196, 0357, 'CY', 'CYP', 'Chipre', 'República do Chipre');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (203, 0420, 'CZ', 'CZE', 'República Tcheca', 'República Tcheca');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (208, 0045, 'DK', 'DNK', 'Dinamarca', 'Reino da Dinamarca');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (262, 0253, 'DJ', 'DJI', 'Djibuti', 'República do Djibuti');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (212, 1767, 'DM', 'DMA', 'Dominica', 'Comunidade da Dominica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (214, 1809, 'DO', 'DOM', 'República Dominicana', 'República Dominicana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (218, 0593, 'EC', 'ECU', 'Equador', 'República do Equador');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (818, 0020, 'EG', 'EGY', 'Egito', 'República Árabe do Egito');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (222, 0503, 'SV', 'SLV', 'El Salvador', 'República El Salvador');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (226, 0240, 'GQ', 'GNQ', 'Guiné Equatorial', 'República do Guiné Equatorial');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (232, 0291, 'ER', 'ERI', 'Eritreia', 'Estado da Eritreia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (233, 0372, 'EE', 'EST', 'Estônia', 'República da Estônia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (231, 0251, 'ET', 'ETH', 'Etiópia', 'República Democrática Federal da Etiópia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (238, 0500, 'FK', 'FLK', 'Ilhas Malvinas', 'Ilhas Malvinas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (234, 0298, 'FO', 'FRO', 'Ilhas Faroe', 'Ilhas Faroe');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (242, 0679, 'FJ', 'FJI', 'Fiji', 'República do Fiji');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (246, 0358, 'FI', 'FIN', 'Finlândia', 'República da Finlândia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (250, 0033, 'FR', 'FRA', 'França', 'República Francesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (254, 0594, 'GF', 'GUF', 'Guiana Francesa', 'Guiana Francesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (258, 0689, 'PF', 'PYF', 'Polinésia Francesa', 'Polinésia Francesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (260, 0033, 'TF', 'ATF', 'Terras Austrais e Antárticas Francesas', 'Território das Terras Austrais e Antárticas Francesas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (266, 0241, 'GA', 'GAB', 'Gabão', 'República Gabonesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (270, 0220, 'GM', 'GMB', 'Gâmbia', 'República da Gâmbia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (268, 0995, 'GE', 'GEO', 'Geórgia', 'Geórgia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (276, 0049, 'DE', 'DEU', 'Alemanha', 'República Federal da Alemanha');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (288, 0233, 'GH', 'GHA', 'Gana', 'Repúblia de Gana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (292, 0350, 'GI', 'GIB', 'Gibraltar', 'Gibraltar');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (300, 0030, 'GR', 'GRC', 'Grécia', 'República Helênica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (304, 0299, 'GL', 'GRL', 'Groelândia', 'Groelândia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (308, 1473, 'GD', 'GRD', 'Granada', 'Granada');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (312, 0590, 'GP', 'GLP', 'Guadalupe', 'Guadalupe');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (316, 1671, 'GU', 'GUM', 'Guão', 'Território do Guão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (320, 0502, 'GT', 'GTM', 'Guatemala', 'República da Guatemala');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (324, 0224, 'GN', 'GIN', 'Guiné', 'República do Guiné');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (624, 0245, 'GW', 'GNB', 'Guiné-Bissau', 'República da Guiné-Bissau');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (328, 0592, 'GY', 'GUY', 'Guiana', 'República Cooperativa da Guiana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (332, 0509, 'HT', 'HTI', 'Haiti', 'República do Haiti');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (334, 0672, 'HM', 'HMD', 'Ilhas Heard e McDonald', 'Território das Ilhas Heard e McDonald');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (336, 0039, 'VA', 'VAT', 'Vaticano', 'Estado da Cidade do Vaticano');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (340, 0504, 'HN', 'HND', 'Honduras', 'República de Honduras');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (344, 0852, 'HK', 'HKG', 'Hong Kong', 'Região Administrativa Especial de Hong Kong da República Popular da China');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (348, 0036, 'HU', 'HUN', 'Hungria', 'Hungria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (352, 0354, 'IS', 'ISL', 'Islândia', 'Islândia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (356, 0091, 'IN', 'IND', 'Índia', 'República da Índia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (360, 0062, 'ID', 'IDN', 'Indonésia', 'República da Indonésia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (364, 0098, 'IR', 'IRN', 'Iran', 'República Islâmica do Iran');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (368, 0964, 'IQ', 'IRQ', 'Iraque', 'República do Iraque');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (372, 0353, 'IE', 'IRL', 'Irlanda', 'Irlanda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (376, 0972, 'IL', 'ISR', 'Israel', 'Estado de Israel');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (380, 0039, 'IT', 'ITA', 'Italia', 'República Italiana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (388, 1876, 'JM', 'JAM', 'Jamaica', 'Jamaica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (392, 0081, 'JP', 'JPN', 'Japão', 'Japão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (400, 0962, 'JO', 'JOR', 'Jornânia', 'Reino Hachemita da Jordânia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (398, 0007, 'KZ', 'KAZ', 'Cazaquistão', 'República do Cazaquistão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (404, 0254, 'KE', 'KEN', 'Quênia', 'República do Quênia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (296, 0686, 'KI', 'KIR', 'Kiribati', 'República do Kiribati');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (408, 0850, 'KP', 'PRK', 'Coreia do Norte', 'República Democrática Popular da Coreia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (410, 0082, 'KR', 'KOR', 'Coreia do Sul', 'República da Coreia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (414, 0965, 'KW', 'KWT', 'Kuwait', 'Estado do Kuwait');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (417, 0996, 'KG', 'KGZ', 'Quirguistão', 'República Quirguiz');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (418, 0856, 'LA', 'LAO', 'Laos', 'República Democrática Popular Lau');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (428, 0371, 'LV', 'LVA', 'Letônia', 'República da Letônia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (422, 0961, 'LB', 'LBN', 'Líbano', 'República Libanesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (426, 0266, 'LS', 'LSO', 'Lesoto', 'Reino do Lesoto');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (430, 0231, 'LR', 'LBR', 'Libéria', 'República da Libéria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (434, 0218, 'LY', 'LBY', 'Líbia', 'Líbia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (438, 0423, 'LI', 'LIE', 'Liechtenstein', 'Principado de Liechtenstein');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (440, 0370, 'LT', 'LTU', 'Lituânia', 'República da Lituânia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (442, 0352, 'LU', 'LUX', 'Luxemburgo', 'Grão-Ducado do Luxemburgo');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (446, 0853, 'MO', 'MAC', 'Macao', 'Macao');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (807, 0389, 'MK', 'MKD', 'Macedônia', 'República da Macedônia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (450, 0261, 'MG', 'MDG', 'Madagascar', 'República de Madagascar');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (454, 0265, 'MW', 'MWI', 'Malawi', 'República de Malawi');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (458, 0060, 'MY', 'MYS', 'Malásia', 'Malásia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (462, 0960, 'MV', 'MDV', 'Maldivas', 'Reública de Maldivas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (466, 0223, 'ML', 'MLI', 'Mali', 'República do Mali');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (470, 0356, 'MT', 'MLT', 'Malta', 'República de Malta');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (584, 0692, 'MH', 'MHL', 'Ilhas Marshall', 'República das Ilhas Marshall');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (474, 0596, 'MQ', 'MTQ', 'Martinica', 'Martinica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (478, 0222, 'MR', 'MRT', 'Mauritânia', 'República Islâmica da Mauritânia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (480, 0230, 'MU', 'MUS', 'Maurício', 'República de Maurício');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (175, 0269, 'YT', 'MYT', 'Mayotte', 'Departamento de Mayotte');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (484, 0052, 'MX', 'MEX', 'México', 'Estados Unidos Mexicanos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (583, 0691, 'FM', 'FSM', 'Micronésia', 'Estados Federados da Micronesia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (498, 0373, 'MD', 'MDA', 'Moldova', 'República de Moldova');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (492, 0377, 'MC', 'MCO', 'Mônaco', 'Principado de Mônaco');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (496, 0976, 'MN', 'MNG', 'Mongólia', 'Mongólia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (500, 1664, 'MS', 'MSR', 'Montserrat', 'Montserrat');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (504, 0212, 'MA', 'MAR', 'Marrocos', 'Reino de Marrocos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (508, 0258, 'MZ', 'MOZ', 'Moçambique', 'República de Moçambique');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (104, 0095, 'MM', 'MMR', 'Birmânia', 'República da União de Myanmar');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (516, 0264, 'NA', 'NAM', 'Namíbia', 'República da Namíbia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (520, 0674, 'NR', 'NRU', 'Nauru', 'República de Nauru');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (524, 0977, 'NP', 'NPL', 'Nepal', 'República Democrática Federativa do Nepal');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (528, 0031, 'NL', 'NLD', 'Holanda', 'Holanda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (530, 0599, 'AN', 'ANT', 'Antilhas Holandesas', 'Antilhas Holandesas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (540, 0687, 'NC', 'NCL', 'Nova Caledônia', 'Nova Caledônia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (554, 0064, 'NZ', 'NZL', 'Nova Zelândia', 'Nova Zelândia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (558, 0505, 'NI', 'NIC', 'Nicarágua', 'República da Nicarágua');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (562, 0227, 'NE', 'NER', 'Niger', 'República do Niger');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (566, 0234, 'NG', 'NGA', 'Nigéria', 'República Federativa da Nigéria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (570, 0683, 'NU', 'NIU', 'Niue', 'Niue');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (574, 0672, 'NF', 'NFK', 'Ilha Norfolk', 'Território da Ilha Norfolk');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (580, 1670, 'MP', 'MNP', 'Ilhas Marianas do Norte', 'Comunidade das Ilhas Marianas do Norte');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (578, 0047, 'NO', 'NOR', 'Noruega', 'Reino da Noruega');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (512, 0968, 'OM', 'OMN', 'Omã', 'Sultanato de Omã');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (586, 0092, 'PK', 'PAK', 'Paquistão', 'República Islâmica do Paquistão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (585, 0680, 'PW', 'PLW', 'Palau', 'República de Palau');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (275, 0970, 'PS', 'PSE', 'Palestina', 'Estado da Palestina');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (591, 0507, 'PA', 'PAN', 'Panamá', 'República do Panamá');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (598, 0675, 'PG', 'PNG', 'Papua-Nova Guiné', 'Estado Independente da Papua-Nova Guiné');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (600, 0595, 'PY', 'PRY', 'Paraguai', 'República do Paraguai');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (604, 0051, 'PE', 'PER', 'Peru', 'República do Peru');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (608, 0063, 'PH', 'PHL', 'Filipinas', 'República das Filipinas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (612, 0672, 'PN', 'PCN', 'Ilhas Picárnia', 'Ilhas Picárnia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (616, 0048, 'PL', 'POL', 'Polônia', 'República da Polônia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (620, 0351, 'PT', 'PRT', 'Portugal', 'República Portuguesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (630, 1787, 'PR', 'PRI', 'Porto Rico', 'Comunidade do Porto Rico');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (634, 0974, 'QA', 'QAT', 'Catar', 'Estado do Catar');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (638, 0262, 'RE', 'REU', 'Reunião', 'Polônia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (642, 0040, 'RO', 'ROM', 'Romênia', 'Romênia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (643, 0070, 'RU', 'RUS', 'Rússia', 'Federação Russa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (646, 0250, 'RW', 'RWA', 'Ruanda', 'República da Ruanda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (654, 0290, 'SH', 'SHN', 'Santa Helena', 'Saint Helena');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (659, 1869, 'KN', 'KNA', 'São Cristóvão', 'São Cristóvão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (662, 1758, 'LC', 'LCA', 'Santa Lúcia', 'Santa Lúcia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (666, 0508, 'PM', 'SPM', 'São Pedro e Miquelon', 'Coletividade Territorial de São Pedro e Miquelon');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (670, 1784, 'VC', 'VCT', 'São Vicente e Granadinas', 'São Vicente e Granadinas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (882, 0684, 'WS', 'WSM', 'Samoa', 'Estado Independente de Samoa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (674, 0378, 'SM', 'SMR', 'São Marino', 'República de São Marino');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (678, 0239, 'ST', 'STP', 'Sao Tomé e Príncipe', 'República Democrática de Sao Tomé e Príncipe');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (682, 0966, 'SA', 'SAU', 'Arábia Saudita', 'Reino da Arábia Saudita');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (686, 0221, 'SN', 'SEN', 'Senegal', 'República do Senegal');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (688, 0381, 'CS', 'SRB', 'Sérvia e Montenegro', 'União Estatal de Sérvia e Montenegro');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (690, 0248, 'SC', 'SYC', 'Seicheles', 'República das Seicheles');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (694, 0232, 'SL', 'SLE', 'República da Serra Leoa', 'República da Serra Leoa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (702, 0065, 'SG', 'SGP', 'Singapura', 'República da Singapura');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (703, 0421, 'SK', 'SVK', 'Eslováquia', 'República Eslovaca');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (705, 0386, 'SI', 'SVN', 'Eslovênia', 'República da Eslovênia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (090, 0677, 'SB', 'SLB', 'Ilhas Salomão', 'Ilhas Salomão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (706, 0252, 'SO', 'SOM', 'Somália', 'República da Somália');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (710, 0027, 'ZA', 'ZAF', 'África do Sul', 'República da África do Sul');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (239, 0500, 'GS', 'SGS', 'Ilhas Geórgia do Sul e Sandwich do Sul', 'Ilhas Geórgia do Sul e Sandwich do Sul');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (724, 0034, 'ES', 'ESP', 'Espanha', 'Reino da Espanha');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (144, 0094, 'LK', 'LKA', 'Sri Lanka', 'República Democrática Socialista do Sri Lanka');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (736, 0249, 'SD', 'SDN', 'Sudão', 'República do Sudão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (740, 0597, 'SR', 'SUR', 'Suriname', 'República do Suriname');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (744, 0047, 'SJ', 'SJM', 'Esvalbarde', 'Esvalbarde');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (748, 0268, 'SZ', 'SWZ', 'Suazilândia', 'Reino da Suazilândia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (752, 0046, 'SE', 'SWE', 'Suécia', 'Reino da Suécia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (756, 0041, 'CH', 'CHE', 'Suiça', 'Confederação Suiça');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (760, 0963, 'SY', 'SYR', 'Síria', 'República Árabe Síria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (158, 0886, 'TW', 'TWN', 'Taiwan', 'Taiwan');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (762, 0992, 'TJ', 'TJK', 'Tajiquistão', 'República do Tajiquistão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (834, 0255, 'TZ', 'TZA', 'Tanzânia', 'República Unida da Tanzânia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (764, 0066, 'TH', 'THA', 'Tailândia', 'Reino da Tailândia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (626, 0670, 'TL', 'TLS', 'Timor-Leste', 'República Democrática de Timor-Leste');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (768, 0228, 'TG', 'TGO', 'Togo', 'República Togolesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (772, 0690, 'TK', 'TKL', 'Toquelau', 'Toquelau');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (776, 0676, 'TO', 'TON', 'Tonga', 'Reino de Tonga');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (780, 1868, 'TT', 'TTO', 'Trinidad e Tobago', 'República da Trinidad e Tobago');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (788, 0216, 'TN', 'TUN', 'Tunísia', 'República da Tunísia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (792, 0090, 'TR', 'TUR', 'Turquia', 'República da Turquia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (795, 7370, 'TM', 'TKM', 'Turcomenistão', 'Turcomenistão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (796, 1649, 'TC', 'TCA', 'Ilhas Turks e Caicos', 'Ilhas Turks e Caicos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (798, 0688, 'TV', 'TUV', 'Tuvalu', 'Tuvalu');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (800, 0256, 'UG', 'UGA', 'Uganda', 'República de Uganda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (804, 0380, 'UA', 'UKR', 'Ucrânia', 'Ucrânia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (784, 0971, 'AE', 'ARE', 'Emirados Árabes', 'Emirados Árabes Unidos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (826, 0044, 'GB', 'GBR', 'Reino Unido', 'Reino Unido da Grã-Bretanha e Irlanda do Norte');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (840, 0001, 'US', 'USA', 'Estados Unidos', 'Estados Unidos da América');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (581, 0001, 'UM', 'UMI', 'Ilhas Menores Distantes dos Estados Unidos', 'Ilhas Menores Distantes dos Estados Unidos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (858, 0598, 'UY', 'URY', 'Uruguai', 'República Oriental do Uruguai');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (860, 0998, 'UZ', 'UZB', 'Uzbequistão', 'República do Uzbequistão');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (548, 0678, 'VU', 'VUT', 'Vanuatu', 'República de Vanuatu');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (862, 0058, 'VE', 'VEN', 'Venezuela', 'República Bolivariana da Venezuela');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (704, 0084, 'VN', 'VNM', 'Vietnam', 'República Socialista do Vietnam');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (092, 1284, 'VG', 'VGB', 'Ilhas Virgens Inglesas', 'Ilhas Virgens');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (850, 1340, 'VI', 'VIR', 'Ilhas Virgens (USA)', 'Ilhas Virgens dos Estados Unidos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (876, 0681, 'WF', 'WLF', 'Wallis e Futuna', 'Wallis e Futuna');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (732, 0212, 'EH', 'ESH', 'Saara Ocidental', 'Saara Ocidental');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (887, 0967, 'YE', 'YEM', 'Iêmen', 'República do Iêmen');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (894, 0260, 'ZM', 'ZMB', 'Zâmbia', 'República do Zâmbia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (716, 0263, 'ZW', 'ZWE', 'Zimbábue', 'República do Zimbábue');

/*
###########################################################################################################################################################
															CRIAÇÃO DA TABELA CADNAVIO
###########################################################################################################################################################
*/

CREATE TABLE CADNAVIO (
    CODIGONAVIO NUMBER(7) NOT NULL,
    DESCRICAO VARCHAR2(120) NOT NULL,
    QTDPORAO NUMBER(10) NOT NULL,
	CAPACIDADEPORAO NUMBER(9,2) NOT NULL,
    CODIGOPAISORIGEM NUMBER(3) NOT NULL,
    
    CONSTRAINT PK_CADNAVIO PRIMARY KEY(CODIGONAVIO),
    CONSTRAINT UN_CADNAVIO_DESCRICAO UNIQUE(DESCRICAO),
    CONSTRAINT FK_CADNAVIO_CADPAIS FOREIGN KEY(CODIGOPAISORIGEM) REFERENCES CADPAIS(CODIGOPAIS)
);



CREATE SEQUENCE SEQ_CODIGO_CADNAVIO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE
    ;

  CREATE OR REPLACE TRIGGER CADNAVIO_CODIGONAVIO_TIGGER
    BEFORE INSERT ON CADNAVIO FOR EACH ROW
  WHEN (NEW.CODIGONAVIO IS NULL OR NEW.CODIGONAVIO = 0)
  BEGIN
    SELECT SEQ_CODIGO_CADNAVIO.NEXTVAL INTO :NEW.CODIGONAVIO FROM dual;
  END;
 
COMMENT ON TABLE CADNAVIO IS 'TABELA DESTINADA AO CADASTRO DOS NAVIOS';
COMMENT ON COLUMN CADNAVIO.CODIGONAVIO IS 'CODIGO DE IDENTIFICAÇÃO DO NAVIO (PRIMARY KEY)';
COMMENT ON COLUMN CADNAVIO.QTDPORAO IS 'QUANTIDADE DE PORÕES QUE O NAVIO POSSUI';
COMMENT ON COLUMN CADNAVIO.CODIGOPAISORIGEM IS 'PAÍS DE ORIGEM DO NAVIO';

/*
###########################################################################################################################################################
															CRIAÇÃO DA TABELA CADUSUARIO
###########################################################################################################################################################
*/

CREATE TABLE GRUPOUSUARIO (
	CODIGOGRUPO NUMBER(3) NOT NULL,
	DESCRICAO VARCHAR2(20) NOT NULL,
	PERMISSAO_INSERT_NAVIO CHAR(1) DEFAULT 'F',
	PERMISSAO_ALTER_NAVIO CHAR(1) DEFAULT 'F',
	PERMISSAO_CONSUL_NAVIO CHAR(1) DEFAULT 'F',
	PERMISSAO_DELET_NAVIO CHAR(1) DEFAULT 'F',
	PERMISSAO_INSERT_USER CHAR(1) DEFAULT 'F',
	PERMISSAO_ALTER_USER CHAR(1) DEFAULT 'F',
	PERMISSAO_CONSUL_USER CHAR(1) DEFAULT 'F',
	PERMISSAO_DELET_USER CHAR(1) DEFAULT 'F',
	PERMISSAO_INSERT_MOVIMENTO CHAR(1) DEFAULT 'F',
	PERMISSAO_ALTER_MOVIMENTO CHAR(1) DEFAULT 'F',
	PERMISSAO_CONSUL_MOVIMENTO CHAR(1) DEFAULT 'F',
	PERMISSAO_DELET_MOVIMENTO CHAR(1) DEFAULT 'F',
	PERMISSAO_INSERT_EMBARQUE CHAR(1) DEFAULT 'F',
	PERMISSAO_ALTER_EMBARQUE CHAR(1) DEFAULT 'F',
	PERMISSAO_CONSUL_EMBARQUE CHAR(1) DEFAULT 'F',
	PERMISSAO_DELET_EMBARQUE CHAR(1) DEFAULT 'F',
	
	CONSTRAINT PK_GRUPOUSUARIO PRIMARY KEY (CODIGOGRUPO),
	CONSTRAINT UN_GRUPOUSUARIO_DESCRICAO UNIQUE(DESCRICAO)
	
);
COMMENT ON TABLE GRUPOUSUARIO IS 'TABELA QUE DEFINE O NÍVEL DE PERMISSÃO DE CADA USUÁRIO';
COMMENT ON COLUMN GRUPOUSUARIO.PERMISSAO IS 'ADM - ADMINISTRADOR, DIR - DIRETOR,SUP - SUPERVISOR, OPR - OPERARIO';
CREATE SEQUENCE SEQ_CODIGO_GRUPOUSUARIO
	START WITH 1
	INCREMENT BY 1
	NOCYCLE
	NOCACHE
	;

CREATE OR REPLACE TRIGGER GRUPOUSUARIO_CODIGO_TIGGER
    BEFORE INSERT ON GRUPOUSUARIO FOR EACH ROW
  WHEN (NEW.CODIGOGRUPO IS NULL OR NEW.CODIGOGRUPO = 0)
  BEGIN
    SELECT SEQ_CODIGO_GRUPOUSUARIO.NEXTVAL INTO :NEW.CODIGOGRUPO FROM dual;
  END;

/*
###########################################################################################################################################################
															CRIAÇÃO DA TABELA CADUSUARIO
###########################################################################################################################################################
*/

CREATE TABLE CADUSUARIO (
	CODIGOUSUARIO NUMBER(3) NOT NULL,
	LOGIN VARCHAR2(10) NOT NULL,
	SENHA VARCHAR2(50) NOT NULL,
	CODIGOGRUPO NUMBER(3) NOT NULL,
	
	CONSTRAINT PK_CADUSUARIO PRIMARY KEY (CODIGOUSUARIO),
	CONSTRAINT UN_CADUSUARIO_LOGIN UNIQUE(LOGIN),
	CONSTRAINT FK_CADUSUARIO_GRUPOUSUARIO FOREIGN KEY(CODIGOGRUPO) REFERENCES GRUPOUSUARIO(CODIGOGRUPO)
);

CREATE SEQUENCE SEQ_CODIGO_CADUSUARIO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE
    ; 
	
CREATE OR REPLACE TRIGGER SEQ_CODIGO_CADUSUARIO
    BEFORE INSERT ON CADUSUARIO FOR EACH ROW
  WHEN (NEW.CODIGOUSUARIO IS NULL OR NEW.CODIGOUSUARIO = 0)
  BEGIN
    SELECT SEQ_CODIGO_CADUSUARIO.NEXTVAL INTO :NEW.CODIGOUSUARIO FROM dual;
  END;
/*
###########################################################################################################################################################
															CRIAÇÃO DA TABELA EMBARQUE
###########################################################################################################################################################
*/


CREATE TABLE EMBARQUE (
    CODIGOEMBARQUE NUMBER(7) NOT NULL,
	CODIGOUSUARIO NUMBER(3) NOT NULL,
    CODIGONAVIO NUMBER(7) NOT NULL,
    CODIGOPAISDESTINO NUMBER(3) NOT NULL,
    STATUS CHAR(1) DEFAULT 'I' NOT NULL,
    QTDAEMBARCAR NUMBER(9,2) NOT NULL,	
    

    CONSTRAINT PK_EMBARQUE PRIMARY KEY(CODIGOEMBARQUE),
	CONSTRAINT FK_EMBARQUE_CADUSUARIO FOREIGN KEY (CODIGOUSUARIO) REFERENCES CADUSUARIO(CODIGOUSUARIO),
	CONSTRAINT FK_CADNAVIO_CADNAVIO FOREIGN KEY (CODIGONAVIO) REFERENCES CADNAVIO(CODIGONAVIO),
    CONSTRAINT FK_CADPAIS_CADPAIS FOREIGN KEY (CODIGOPAISDESTINO) REFERENCES CADPAIS(CODIGOPAIS),
    CONSTRAINT CK_EMBARQUE_STATUS CHECK(STATUS IN('I','P','F','C'))
);
CREATE SEQUENCE SEQ_CODIGO_EMBARQUE
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE
	;

CREATE OR REPLACE TRIGGER SEQ_CODIGO_EMBARQUE
    BEFORE INSERT ON EMBARQUE FOR EACH ROW
  WHEN (NEW.CODIGOEMBARQUE IS NULL OR NEW.CODIGOEMBARQUE = 0)
  BEGIN
    SELECT SEQ_CODIGO_EMBARQUE.NEXTVAL INTO :NEW.CODIGOEMBARQUE FROM dual;
  END;
COMMENT ON TABLE EMBARQUE IS 'TABELA PRINCIPAL DO SISTEMA, ONDE SÃO REGISTRADOS TODOS OS EMBARQUES';
COMMENT ON COLUMN EMBARQUE.STATUS IS 'I - INICIADO, P - PAUSADO, F - FINALIZADO, C - CANCELADO';


CREATE TABLE MOVEMBARQUE (
	CODIGOMOVEMBARQUE NUMBER(10) NOT NULL,
	CODIGOEMBARQUE NUMBER(7) NOT NULL,
	CODIGOUSUARIO NUMBER(7) NOT NULL,
	PAUSA CHAR(1) NOT NULL,
	DATAINICIOMOVIMENTO DATE NOT NULL,
	DATAFIMMOVIMENTO DATE,
	CANCELADO CHAR(1) DEFAULT 'F' NOT NULL,
	MOTIVOCANCELAMENTO VARCHAR2(120),
	
	CONSTRAINT PK_MOVEMBARQUE PRIMARY KEY (CODIGOMOVEMBARQUE, PAUSA),
	CONSTRAINT FK_MOVEMBARQUE_PAUSA FOREIGN KEY (PAUSA) REFERENCES PAUSA(CODIGOPAUSA),
	CONSTRAINT FK_MOVEMBARQUE_EMBARQUE FOREIGN KEY (CODIGOEMBARQUE) REFERENCES EMBARQUE (CODIGOEMBARQUE),
	CONSTRAINT FK_MOVEMBARQUE_CADUSUARIO FOREIGN KEY (CODIGOUSUARIO) REFERENCES CADUSUARIO (CODIGOUSUARIO),
	CONSTRAINT CK_MOVEMBARQUE_PAUSA CHECK (PAUSA IN ('I','F'))
);
COMMENT ON TABLE MOVEMBARQUE IS 'TABELA QUE IRÁ CONTER TODA MOVIMENTAÇÃO DOS EMBARQUES';
COMMENT ON COLUMN MOVEMBARQUE.CODIGOEMBARQUE IS 'INDICA A QUAL EMBARQUE ESSE MOVIMENTO PERTENCE';
COMMENT ON COLUMN MOVEMBARQUE.CODIGOUSUARIO IS 'INDICA QUAL USUÁRIO EFETUOU A MOVIMENTAÇÃO';
COMMENT ON COLUMN MOVEMBARQUE.PAUSA IS 'I - INICIADO,  F - FINALIZADO';

CREATE SEQUENCE SEQ_CODIGO_MOVIMENTOEMBARQUE
	START WITH 1
	INCREMENT BY 1
	NOCYCLE
	NOCACHE
	;
CREATE TABLE CADPAUSA(
    CODIGOPAUSA NUMBER(7),
    DESCRICAO VARCHAR2(50),

    CONSTRAINT PK_PAUSA PRIMARY KEY (CODIGOPAUSA),
    CONSTRAINT UN_PAUSA_DESCRICAO UNIQUE (DESCRICAO)
);
CREATE SEQUENCE SEQ_CODIGO_CADPAUSA
	START WITH 1
	INCREMENT BY 1
	NOCYCLE
	NOCACHE
	;
--VERIFICAR
/*
CREATE TABLE LOG_ACAO
(	
	TABLE_NAME VARCHAR2(30) NOT NULL,
	CODIGO_USUARIO NUMBER,
	timestamp date,
	ACAO CHAR(1) NOT NULL CHECK (ACAO IN ('I','D','U')),
	INF_ANTERIOR VARCHAR2(30),
	INF_ATUAL VARCHAR2(30),
	QUERY VARCHAR2(100)
)
----------------------------------------------------------
CREATE TABLE LOG_ACAO
(	
	TABLE_NAME VARCHAR2(30) NOT NULL,
	CODIGO_USUARIO NUMBER,
	timestamp date,
	ACAO CHAR(1) NOT NULL CHECK (ACAO IN ('I','D','U')),
	INF_ANTERIOR VARCHAR2(30),
	INF_ATUAL VARCHAR2(30),
	QUERY VARCHAR2(100)
)

CREATE OR REPLACE TRIGGER CADNAVIO_LOG_ACAO

   AFTER INSERT OR UPDATE OR DELETE ON CADNAVIO

     FOR EACH ROW

 DECLARE


   ACAO LOG_ACAO.ACAO%TYPE;

 BEGIN

   IF INSERTING THEN 


      ACAO := 'I';

   ELSIF DELETING THEN

     ACAO := 'D';


   ELSIF UPDATING THEN


    ACAO := 'U';

   END IF;

 


INSERT INTO LOG_ACAO
(	
	TABLE_NAME,
	CODIGO_USUARIO,
	timestamp,
	ACAO,
	INF_ANTERIOR,
	INF_ATUAL,
	QUERY
)VALUES
(
	'CADNAVIO',
	CODIGONAVIO,
	SYSDATE,
	ACAO,
	:OLD.DESCRICAO,
    :NEW.DESCRICAO,
	'FALTA COLOCAR COMANDO SQL'
);

END;
*/	