/*
###########################################################################################################################################################
															CRIAÃ‡ÃƒO DA TABELA CADPAIS
###########################################################################################################################################################
*/


CREATE TABLE CADPAIS (
    CODIGOPAIS NUMBER(3) NOT NULL,
    DDI VARCHAR2(4) NOT NULL,
    ISO VARCHAR2(2) NOT NULL,
    ISO3 VARCHAR2(3) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    NOMEFORMAL VARCHAR2(100) NOT NULL,
    
    CONSTRAINT PK_CADPAIS PRIMARY KEY (CODIGOPAIS),
    CONSTRAINT UN_CADPAIS_ISO UNIQUE(ISO,ISO3),
    CONSTRAINT UN_CADPAIS_NOME UNIQUE(NOME,NOMEFORMAL)
);

/* COMENTÃRIOS DE TABELAS E COLUNAS*/

COMMENT ON TABLE CADPAIS IS 'TABELA DESTINADA AO CADASTRO DE PAISES';
COMMENT ON COLUMN CADPAIS.CODIGOPAIS IS 'CODIGO INTERNACIONAL DO PAÃS (PRIMARY KEY)';
COMMENT ON COLUMN CADPAIS.ISO IS 'SIGLA EM 2 LETRAS DE CADA PAÃS';
COMMENT ON COLUMN CADPAIS.ISO3 IS 'SIGLA EM 3 LETRAS DE CADA PAÃS';
COMMENT ON COLUMN CADPAIS.NOME IS 'NOME POPULAR DO PAÃS';
COMMENT ON COLUMN CADPAIS.NOMEFORMAL IS 'NOME FORMAL DO PAÃS';

/* INSERÃ‡ÃƒO DOS DADOS FIXOS NA TABELA CADPAIS */

INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (004, 0093, 'AF', 'AFG', 'AfeganistÃ£o', 'RepÃºblica IslÃ¢mica do AfeganistÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (008, 0355, 'AL', 'ALB', 'AlbÃ¢nia', 'RepÃºblica da AlbÃ¢nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (012, 0213, 'DZ', 'DZA', 'AlgÃ©ria', 'RepÃºblica DemocrÃ¡tica Popular da AlgÃ©ria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (016, 1684, 'AS', 'ASM', 'Samoa Americana', 'TerritÃ³rio de Samoa Americana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (020, 0376, 'AD', 'AND', 'Andorra', 'Principado Andorra');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (024, 0244, 'AO', 'AGO', 'Angola', 'RepÃºblica de Angola');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (660, 1264, 'AI', 'AIA', 'Anguilla', 'Anguilla');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (010, 0672, 'AQ', 'ATA', 'AntÃ¡rtida', 'AntÃ¡rtida');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (028, 1268, 'AG', 'ATG', 'Antigua e Barbuda', 'Antigua e Barbuda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (032, 0054, 'AR', 'ARG', 'Argentina', 'RepÃºblica Argentina');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (051, 0374, 'AM', 'ARM', 'ArmÃªnia', 'RepÃºblica da ArmÃªnia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (533, 0297, 'AW', 'ABW', 'Aruba', 'Aruba');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (036, 0061, 'AU', 'AUS', 'AustrÃ¡lia', 'Comunidade da AustrÃ¡lia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (040, 0043, 'AT', 'AUT', 'Ãustria', 'RepÃºblica da Ãustria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (031, 0994, 'AZ', 'AZE', 'AzerbaijÃ£o', 'RepÃºblica do AzerbaijÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (044, 1242, 'BS', 'BHS', 'Bahamas', 'Comunidade de Bahamas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (048, 0973, 'BH', 'BHR', 'Bahrein', 'Reino do Bahrein');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (050, 0880, 'BD', 'BGD', 'Bangladesh', 'RepÃºblica Popular de Bangladesh');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (052, 0246, 'BB', 'BRB', 'Barbados', 'Barbados');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (112, 0375, 'BY', 'BLR', 'BielorrÃºssia', 'RepÃºblica da BielorrÃºssia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (056, 0032, 'BE', 'BEL', 'BÃ©lgica', 'Reino da BÃ©lgica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (084, 0501, 'BZ', 'BLZ', 'Belize', 'Belize');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (204, 0229, 'BJ', 'BEN', 'Benin', 'RepÃºblica do Benin');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (060, 1441, 'BM', 'BMU', 'Bermuda', 'Bermuda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (064, 0975, 'BT', 'BTN', 'ButÃ£o', 'Reino do ButÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (068, 0591, 'BO', 'BOL', 'BolÃ­via', 'Estado Plurinacional da BolÃ­via');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (070, 0387, 'BA', 'BIH', 'BÃ³snia e Herzegovina', 'BÃ³snia e Herzegovina');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (072, 0267, 'BW', 'BWA', 'Botswana', 'RepÃºblica da Botswana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (074, 0047, 'BV', 'BVT', 'Ilha Bouvet', 'Ilha Bouvet');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (076, 0055, 'BR', 'BRA', 'Brasil', 'RepÃºblica Federativa do Brasil');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (086, 0246, 'IO', 'IOT', 'TerritÃ³rio BritÃ¢nico do Oceano Ãndico', 'TerritÃ³rio BritÃ¢nico do Oceano Ãndico');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (096, 0673, 'BN', 'BRN', 'Brunei', 'Estado do Brunei Darussalam');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (100, 0359, 'BG', 'BGR', 'BulgÃ¡ria', 'RepÃºblica da BulgÃ¡ria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (854, 0226, 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (108, 0257, 'BI', 'BDI', 'Burundi', 'RepÃºblica do Burundi');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (116, 0855, 'KH', 'KHM', 'Camboja', 'Reino do Camboja');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (120, 0237, 'CM', 'CMR', 'CamarÃµes', 'RepÃºblica de CamarÃµes');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (124, 0001, 'CA', 'CAN', 'CanadÃ¡', 'CanadÃ¡');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (132, 0238, 'CV', 'CPV', 'Cabo Verde', 'RepÃºblica do Cabo Verde');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (136, 1345, 'KY', 'CYM', 'Ilhas Cayman', 'Ilhas Cayman');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (140, 0236, 'CF', 'CAF', 'RepÃºblica Centro-Africana', 'RepÃºblica Centro-Africana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (148, 0235, 'TD', 'TCD', 'Chade', 'RepÃºblica do Chade');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (152, 0056, 'CL', 'CHL', 'Chile', 'RepÃºblica do Chile');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (156, 0086, 'CN', 'CHN', 'China', 'RepÃºblica Popular da China');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (162, 0061, 'CX', 'CXR', 'Ilha Christmas', 'TerritÃ³rio da Ilha Christmas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (166, 0672, 'CC', 'CCK', 'Ilhas Cocos (Keeling)', 'TerritÃ³rio das Ilhas Cocos (Keeling)');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (170, 0057, 'CO', 'COL', 'ColÃ´mbia', 'RepÃºblica da ColÃ´mbia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (174, 0269, 'KM', 'COM', 'Comores', 'UniÃ£o das Comores');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (178, 0242, 'CG', 'COG', 'Congo', 'RepÃºblica do Congo');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (180, 0242, 'CD', 'COD', 'Congo (DR)', 'RepÃºblica DemocrÃ¡tica do Congo');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (184, 0682, 'CK', 'COK', 'Ilhas Cook', 'Ilhas Cook');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (188, 0506, 'CR', 'CRI', 'Costa Rica', 'RepÃºblica da Costa Rica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (384, 0225, 'CI', 'CIV', 'Costa do Marfim', 'RepÃºblica da Costa do Marfim');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (191, 0385, 'HR', 'HRV', 'CroÃ¡cia', 'RepÃºblica da CroÃ¡cia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (192, 0053, 'CU', 'CUB', 'Cuba', 'RepÃºblica de Cuba');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (196, 0357, 'CY', 'CYP', 'Chipre', 'RepÃºblica do Chipre');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (203, 0420, 'CZ', 'CZE', 'RepÃºblica Tcheca', 'RepÃºblica Tcheca');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (208, 0045, 'DK', 'DNK', 'Dinamarca', 'Reino da Dinamarca');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (262, 0253, 'DJ', 'DJI', 'Djibuti', 'RepÃºblica do Djibuti');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (212, 1767, 'DM', 'DMA', 'Dominica', 'Comunidade da Dominica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (214, 1809, 'DO', 'DOM', 'RepÃºblica Dominicana', 'RepÃºblica Dominicana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (218, 0593, 'EC', 'ECU', 'Equador', 'RepÃºblica do Equador');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (818, 0020, 'EG', 'EGY', 'Egito', 'RepÃºblica Ãrabe do Egito');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (222, 0503, 'SV', 'SLV', 'El Salvador', 'RepÃºblica El Salvador');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (226, 0240, 'GQ', 'GNQ', 'GuinÃ© Equatorial', 'RepÃºblica do GuinÃ© Equatorial');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (232, 0291, 'ER', 'ERI', 'Eritreia', 'Estado da Eritreia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (233, 0372, 'EE', 'EST', 'EstÃ´nia', 'RepÃºblica da EstÃ´nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (231, 0251, 'ET', 'ETH', 'EtiÃ³pia', 'RepÃºblica DemocrÃ¡tica Federal da EtiÃ³pia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (238, 0500, 'FK', 'FLK', 'Ilhas Malvinas', 'Ilhas Malvinas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (234, 0298, 'FO', 'FRO', 'Ilhas Faroe', 'Ilhas Faroe');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (242, 0679, 'FJ', 'FJI', 'Fiji', 'RepÃºblica do Fiji');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (246, 0358, 'FI', 'FIN', 'FinlÃ¢ndia', 'RepÃºblica da FinlÃ¢ndia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (250, 0033, 'FR', 'FRA', 'FranÃ§a', 'RepÃºblica Francesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (254, 0594, 'GF', 'GUF', 'Guiana Francesa', 'Guiana Francesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (258, 0689, 'PF', 'PYF', 'PolinÃ©sia Francesa', 'PolinÃ©sia Francesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (260, 0033, 'TF', 'ATF', 'Terras Austrais e AntÃ¡rticas Francesas', 'TerritÃ³rio das Terras Austrais e AntÃ¡rticas Francesas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (266, 0241, 'GA', 'GAB', 'GabÃ£o', 'RepÃºblica Gabonesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (270, 0220, 'GM', 'GMB', 'GÃ¢mbia', 'RepÃºblica da GÃ¢mbia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (268, 0995, 'GE', 'GEO', 'GeÃ³rgia', 'GeÃ³rgia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (276, 0049, 'DE', 'DEU', 'Alemanha', 'RepÃºblica Federal da Alemanha');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (288, 0233, 'GH', 'GHA', 'Gana', 'RepÃºblia de Gana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (292, 0350, 'GI', 'GIB', 'Gibraltar', 'Gibraltar');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (300, 0030, 'GR', 'GRC', 'GrÃ©cia', 'RepÃºblica HelÃªnica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (304, 0299, 'GL', 'GRL', 'GroelÃ¢ndia', 'GroelÃ¢ndia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (308, 1473, 'GD', 'GRD', 'Granada', 'Granada');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (312, 0590, 'GP', 'GLP', 'Guadalupe', 'Guadalupe');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (316, 1671, 'GU', 'GUM', 'GuÃ£o', 'TerritÃ³rio do GuÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (320, 0502, 'GT', 'GTM', 'Guatemala', 'RepÃºblica da Guatemala');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (324, 0224, 'GN', 'GIN', 'GuinÃ©', 'RepÃºblica do GuinÃ©');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (624, 0245, 'GW', 'GNB', 'GuinÃ©-Bissau', 'RepÃºblica da GuinÃ©-Bissau');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (328, 0592, 'GY', 'GUY', 'Guiana', 'RepÃºblica Cooperativa da Guiana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (332, 0509, 'HT', 'HTI', 'Haiti', 'RepÃºblica do Haiti');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (334, 0672, 'HM', 'HMD', 'Ilhas Heard e McDonald', 'TerritÃ³rio das Ilhas Heard e McDonald');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (336, 0039, 'VA', 'VAT', 'Vaticano', 'Estado da Cidade do Vaticano');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (340, 0504, 'HN', 'HND', 'Honduras', 'RepÃºblica de Honduras');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (344, 0852, 'HK', 'HKG', 'Hong Kong', 'RegiÃ£o Administrativa Especial de Hong Kong da RepÃºblica Popular da China');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (348, 0036, 'HU', 'HUN', 'Hungria', 'Hungria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (352, 0354, 'IS', 'ISL', 'IslÃ¢ndia', 'IslÃ¢ndia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (356, 0091, 'IN', 'IND', 'Ãndia', 'RepÃºblica da Ãndia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (360, 0062, 'ID', 'IDN', 'IndonÃ©sia', 'RepÃºblica da IndonÃ©sia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (364, 0098, 'IR', 'IRN', 'Iran', 'RepÃºblica IslÃ¢mica do Iran');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (368, 0964, 'IQ', 'IRQ', 'Iraque', 'RepÃºblica do Iraque');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (372, 0353, 'IE', 'IRL', 'Irlanda', 'Irlanda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (376, 0972, 'IL', 'ISR', 'Israel', 'Estado de Israel');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (380, 0039, 'IT', 'ITA', 'Italia', 'RepÃºblica Italiana');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (388, 1876, 'JM', 'JAM', 'Jamaica', 'Jamaica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (392, 0081, 'JP', 'JPN', 'JapÃ£o', 'JapÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (400, 0962, 'JO', 'JOR', 'JornÃ¢nia', 'Reino Hachemita da JordÃ¢nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (398, 0007, 'KZ', 'KAZ', 'CazaquistÃ£o', 'RepÃºblica do CazaquistÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (404, 0254, 'KE', 'KEN', 'QuÃªnia', 'RepÃºblica do QuÃªnia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (296, 0686, 'KI', 'KIR', 'Kiribati', 'RepÃºblica do Kiribati');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (408, 0850, 'KP', 'PRK', 'Coreia do Norte', 'RepÃºblica DemocrÃ¡tica Popular da Coreia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (410, 0082, 'KR', 'KOR', 'Coreia do Sul', 'RepÃºblica da Coreia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (414, 0965, 'KW', 'KWT', 'Kuwait', 'Estado do Kuwait');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (417, 0996, 'KG', 'KGZ', 'QuirguistÃ£o', 'RepÃºblica Quirguiz');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (418, 0856, 'LA', 'LAO', 'Laos', 'RepÃºblica DemocrÃ¡tica Popular Lau');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (428, 0371, 'LV', 'LVA', 'LetÃ´nia', 'RepÃºblica da LetÃ´nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (422, 0961, 'LB', 'LBN', 'LÃ­bano', 'RepÃºblica Libanesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (426, 0266, 'LS', 'LSO', 'Lesoto', 'Reino do Lesoto');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (430, 0231, 'LR', 'LBR', 'LibÃ©ria', 'RepÃºblica da LibÃ©ria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (434, 0218, 'LY', 'LBY', 'LÃ­bia', 'LÃ­bia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (438, 0423, 'LI', 'LIE', 'Liechtenstein', 'Principado de Liechtenstein');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (440, 0370, 'LT', 'LTU', 'LituÃ¢nia', 'RepÃºblica da LituÃ¢nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (442, 0352, 'LU', 'LUX', 'Luxemburgo', 'GrÃ£o-Ducado do Luxemburgo');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (446, 0853, 'MO', 'MAC', 'Macao', 'Macao');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (807, 0389, 'MK', 'MKD', 'MacedÃ´nia', 'RepÃºblica da MacedÃ´nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (450, 0261, 'MG', 'MDG', 'Madagascar', 'RepÃºblica de Madagascar');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (454, 0265, 'MW', 'MWI', 'Malawi', 'RepÃºblica de Malawi');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (458, 0060, 'MY', 'MYS', 'MalÃ¡sia', 'MalÃ¡sia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (462, 0960, 'MV', 'MDV', 'Maldivas', 'ReÃºblica de Maldivas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (466, 0223, 'ML', 'MLI', 'Mali', 'RepÃºblica do Mali');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (470, 0356, 'MT', 'MLT', 'Malta', 'RepÃºblica de Malta');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (584, 0692, 'MH', 'MHL', 'Ilhas Marshall', 'RepÃºblica das Ilhas Marshall');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (474, 0596, 'MQ', 'MTQ', 'Martinica', 'Martinica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (478, 0222, 'MR', 'MRT', 'MauritÃ¢nia', 'RepÃºblica IslÃ¢mica da MauritÃ¢nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (480, 0230, 'MU', 'MUS', 'MaurÃ­cio', 'RepÃºblica de MaurÃ­cio');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (175, 0269, 'YT', 'MYT', 'Mayotte', 'Departamento de Mayotte');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (484, 0052, 'MX', 'MEX', 'MÃ©xico', 'Estados Unidos Mexicanos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (583, 0691, 'FM', 'FSM', 'MicronÃ©sia', 'Estados Federados da Micronesia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (498, 0373, 'MD', 'MDA', 'Moldova', 'RepÃºblica de Moldova');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (492, 0377, 'MC', 'MCO', 'MÃ´naco', 'Principado de MÃ´naco');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (496, 0976, 'MN', 'MNG', 'MongÃ³lia', 'MongÃ³lia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (500, 1664, 'MS', 'MSR', 'Montserrat', 'Montserrat');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (504, 0212, 'MA', 'MAR', 'Marrocos', 'Reino de Marrocos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (508, 0258, 'MZ', 'MOZ', 'MoÃ§ambique', 'RepÃºblica de MoÃ§ambique');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (104, 0095, 'MM', 'MMR', 'BirmÃ¢nia', 'RepÃºblica da UniÃ£o de Myanmar');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (516, 0264, 'NA', 'NAM', 'NamÃ­bia', 'RepÃºblica da NamÃ­bia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (520, 0674, 'NR', 'NRU', 'Nauru', 'RepÃºblica de Nauru');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (524, 0977, 'NP', 'NPL', 'Nepal', 'RepÃºblica DemocrÃ¡tica Federativa do Nepal');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (528, 0031, 'NL', 'NLD', 'Holanda', 'Holanda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (530, 0599, 'AN', 'ANT', 'Antilhas Holandesas', 'Antilhas Holandesas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (540, 0687, 'NC', 'NCL', 'Nova CaledÃ´nia', 'Nova CaledÃ´nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (554, 0064, 'NZ', 'NZL', 'Nova ZelÃ¢ndia', 'Nova ZelÃ¢ndia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (558, 0505, 'NI', 'NIC', 'NicarÃ¡gua', 'RepÃºblica da NicarÃ¡gua');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (562, 0227, 'NE', 'NER', 'Niger', 'RepÃºblica do Niger');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (566, 0234, 'NG', 'NGA', 'NigÃ©ria', 'RepÃºblica Federativa da NigÃ©ria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (570, 0683, 'NU', 'NIU', 'Niue', 'Niue');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (574, 0672, 'NF', 'NFK', 'Ilha Norfolk', 'TerritÃ³rio da Ilha Norfolk');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (580, 1670, 'MP', 'MNP', 'Ilhas Marianas do Norte', 'Comunidade das Ilhas Marianas do Norte');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (578, 0047, 'NO', 'NOR', 'Noruega', 'Reino da Noruega');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (512, 0968, 'OM', 'OMN', 'OmÃ£', 'Sultanato de OmÃ£');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (586, 0092, 'PK', 'PAK', 'PaquistÃ£o', 'RepÃºblica IslÃ¢mica do PaquistÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (585, 0680, 'PW', 'PLW', 'Palau', 'RepÃºblica de Palau');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (275, 0970, 'PS', 'PSE', 'Palestina', 'Estado da Palestina');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (591, 0507, 'PA', 'PAN', 'PanamÃ¡', 'RepÃºblica do PanamÃ¡');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (598, 0675, 'PG', 'PNG', 'Papua-Nova GuinÃ©', 'Estado Independente da Papua-Nova GuinÃ©');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (600, 0595, 'PY', 'PRY', 'Paraguai', 'RepÃºblica do Paraguai');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (604, 0051, 'PE', 'PER', 'Peru', 'RepÃºblica do Peru');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (608, 0063, 'PH', 'PHL', 'Filipinas', 'RepÃºblica das Filipinas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (612, 0672, 'PN', 'PCN', 'Ilhas PicÃ¡rnia', 'Ilhas PicÃ¡rnia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (616, 0048, 'PL', 'POL', 'PolÃ´nia', 'RepÃºblica da PolÃ´nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (620, 0351, 'PT', 'PRT', 'Portugal', 'RepÃºblica Portuguesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (630, 1787, 'PR', 'PRI', 'Porto Rico', 'Comunidade do Porto Rico');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (634, 0974, 'QA', 'QAT', 'Catar', 'Estado do Catar');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (638, 0262, 'RE', 'REU', 'ReuniÃ£o', 'PolÃ´nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (642, 0040, 'RO', 'ROM', 'RomÃªnia', 'RomÃªnia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (643, 0070, 'RU', 'RUS', 'RÃºssia', 'FederaÃ§Ã£o Russa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (646, 0250, 'RW', 'RWA', 'Ruanda', 'RepÃºblica da Ruanda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (654, 0290, 'SH', 'SHN', 'Santa Helena', 'Saint Helena');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (659, 1869, 'KN', 'KNA', 'SÃ£o CristÃ³vÃ£o', 'SÃ£o CristÃ³vÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (662, 1758, 'LC', 'LCA', 'Santa LÃºcia', 'Santa LÃºcia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (666, 0508, 'PM', 'SPM', 'SÃ£o Pedro e Miquelon', 'Coletividade Territorial de SÃ£o Pedro e Miquelon');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (670, 1784, 'VC', 'VCT', 'SÃ£o Vicente e Granadinas', 'SÃ£o Vicente e Granadinas');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (882, 0684, 'WS', 'WSM', 'Samoa', 'Estado Independente de Samoa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (674, 0378, 'SM', 'SMR', 'SÃ£o Marino', 'RepÃºblica de SÃ£o Marino');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (678, 0239, 'ST', 'STP', 'Sao TomÃ© e PrÃ­ncipe', 'RepÃºblica DemocrÃ¡tica de Sao TomÃ© e PrÃ­ncipe');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (682, 0966, 'SA', 'SAU', 'ArÃ¡bia Saudita', 'Reino da ArÃ¡bia Saudita');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (686, 0221, 'SN', 'SEN', 'Senegal', 'RepÃºblica do Senegal');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (688, 0381, 'CS', 'SRB', 'SÃ©rvia e Montenegro', 'UniÃ£o Estatal de SÃ©rvia e Montenegro');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (690, 0248, 'SC', 'SYC', 'Seicheles', 'RepÃºblica das Seicheles');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (694, 0232, 'SL', 'SLE', 'RepÃºblica da Serra Leoa', 'RepÃºblica da Serra Leoa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (702, 0065, 'SG', 'SGP', 'Singapura', 'RepÃºblica da Singapura');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (703, 0421, 'SK', 'SVK', 'EslovÃ¡quia', 'RepÃºblica Eslovaca');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (705, 0386, 'SI', 'SVN', 'EslovÃªnia', 'RepÃºblica da EslovÃªnia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (090, 0677, 'SB', 'SLB', 'Ilhas SalomÃ£o', 'Ilhas SalomÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (706, 0252, 'SO', 'SOM', 'SomÃ¡lia', 'RepÃºblica da SomÃ¡lia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (710, 0027, 'ZA', 'ZAF', 'Ãfrica do Sul', 'RepÃºblica da Ãfrica do Sul');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (239, 0500, 'GS', 'SGS', 'Ilhas GeÃ³rgia do Sul e Sandwich do Sul', 'Ilhas GeÃ³rgia do Sul e Sandwich do Sul');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (724, 0034, 'ES', 'ESP', 'Espanha', 'Reino da Espanha');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (144, 0094, 'LK', 'LKA', 'Sri Lanka', 'RepÃºblica DemocrÃ¡tica Socialista do Sri Lanka');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (736, 0249, 'SD', 'SDN', 'SudÃ£o', 'RepÃºblica do SudÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (740, 0597, 'SR', 'SUR', 'Suriname', 'RepÃºblica do Suriname');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (744, 0047, 'SJ', 'SJM', 'Esvalbarde', 'Esvalbarde');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (748, 0268, 'SZ', 'SWZ', 'SuazilÃ¢ndia', 'Reino da SuazilÃ¢ndia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (752, 0046, 'SE', 'SWE', 'SuÃ©cia', 'Reino da SuÃ©cia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (756, 0041, 'CH', 'CHE', 'SuiÃ§a', 'ConfederaÃ§Ã£o SuiÃ§a');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (760, 0963, 'SY', 'SYR', 'SÃ­ria', 'RepÃºblica Ãrabe SÃ­ria');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (158, 0886, 'TW', 'TWN', 'Taiwan', 'Taiwan');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (762, 0992, 'TJ', 'TJK', 'TajiquistÃ£o', 'RepÃºblica do TajiquistÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (834, 0255, 'TZ', 'TZA', 'TanzÃ¢nia', 'RepÃºblica Unida da TanzÃ¢nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (764, 0066, 'TH', 'THA', 'TailÃ¢ndia', 'Reino da TailÃ¢ndia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (626, 0670, 'TL', 'TLS', 'Timor-Leste', 'RepÃºblica DemocrÃ¡tica de Timor-Leste');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (768, 0228, 'TG', 'TGO', 'Togo', 'RepÃºblica Togolesa');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (772, 0690, 'TK', 'TKL', 'Toquelau', 'Toquelau');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (776, 0676, 'TO', 'TON', 'Tonga', 'Reino de Tonga');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (780, 1868, 'TT', 'TTO', 'Trinidad e Tobago', 'RepÃºblica da Trinidad e Tobago');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (788, 0216, 'TN', 'TUN', 'TunÃ­sia', 'RepÃºblica da TunÃ­sia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (792, 0090, 'TR', 'TUR', 'Turquia', 'RepÃºblica da Turquia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (795, 7370, 'TM', 'TKM', 'TurcomenistÃ£o', 'TurcomenistÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (796, 1649, 'TC', 'TCA', 'Ilhas Turks e Caicos', 'Ilhas Turks e Caicos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (798, 0688, 'TV', 'TUV', 'Tuvalu', 'Tuvalu');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (800, 0256, 'UG', 'UGA', 'Uganda', 'RepÃºblica de Uganda');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (804, 0380, 'UA', 'UKR', 'UcrÃ¢nia', 'UcrÃ¢nia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (784, 0971, 'AE', 'ARE', 'Emirados Ãrabes', 'Emirados Ãrabes Unidos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (826, 0044, 'GB', 'GBR', 'Reino Unido', 'Reino Unido da GrÃ£-Bretanha e Irlanda do Norte');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (840, 0001, 'US', 'USA', 'Estados Unidos', 'Estados Unidos da AmÃ©rica');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (581, 0001, 'UM', 'UMI', 'Ilhas Menores Distantes dos Estados Unidos', 'Ilhas Menores Distantes dos Estados Unidos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (858, 0598, 'UY', 'URY', 'Uruguai', 'RepÃºblica Oriental do Uruguai');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (860, 0998, 'UZ', 'UZB', 'UzbequistÃ£o', 'RepÃºblica do UzbequistÃ£o');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (548, 0678, 'VU', 'VUT', 'Vanuatu', 'RepÃºblica de Vanuatu');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (862, 0058, 'VE', 'VEN', 'Venezuela', 'RepÃºblica Bolivariana da Venezuela');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (704, 0084, 'VN', 'VNM', 'Vietnam', 'RepÃºblica Socialista do Vietnam');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (092, 1284, 'VG', 'VGB', 'Ilhas Virgens Inglesas', 'Ilhas Virgens');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (850, 1340, 'VI', 'VIR', 'Ilhas Virgens (USA)', 'Ilhas Virgens dos Estados Unidos');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (876, 0681, 'WF', 'WLF', 'Wallis e Futuna', 'Wallis e Futuna');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (732, 0212, 'EH', 'ESH', 'Saara Ocidental', 'Saara Ocidental');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (887, 0967, 'YE', 'YEM', 'IÃªmen', 'RepÃºblica do IÃªmen');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (894, 0260, 'ZM', 'ZMB', 'ZÃ¢mbia', 'RepÃºblica do ZÃ¢mbia');
INSERT INTO CADPAIS (CODIGOPAIS, DDI, ISO, ISO3, NOME, NOMEFORMAL) VALUES (716, 0263, 'ZW', 'ZWE', 'ZimbÃ¡bue', 'RepÃºblica do ZimbÃ¡bue');

/*
###########################################################################################################################################################
															CRIAÃ‡ÃƒO DA TABELA CADNAVIO
###########################################################################################################################################################
*/

CREATE TABLE CADNAVIO (
    CODIGONAVIO NUMBER(7) NOT NULL,
    DESCRICAO VARCHAR2(120) NOT NULL,
    QTDPORAO NUMBER(10) NOT NULL,
    CODIGOPAISORIGEM NUMBER(3) NOT NULL,
    
    CONSTRAINT PK_CADNAVIO PRIMARY KEY(CODIGONAVIO),
    CONSTRAINT UN_CADNAVIO_DESCRICAO UNIQUE(DESCRICAO),
    CONSTRAINT FK_CADNAVIO_CADPAIS FOREIGN KEY(CODIGOPAISORIGEM) REFERENCES CADPAIS(CODIGOPAIS)
);



CREATE SEQUENCE SEQ_CODIGO_CADNAVIO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE
    ;

  CREATE OR REPLACE TRIGGER CADNAVIO_CODIGONAVIO_TIGGER
    BEFORE INSERT ON CADNAVIO FOR EACH ROW
  WHEN (NEW.CODIGONAVIO IS NULL OR NEW.CODIGONAVIO = 0)
  BEGIN
    SELECT SEQ_CODIGO_CADNAVIO.NEXTVAL INTO :NEW.CODIGONAVIO FROM dual;
  END;
 
COMMENT ON TABLE CADNAVIO IS 'TABELA DESTINADA AO CADASTRO DOS NAVIOS';
COMMENT ON COLUMN CADNAVIO.CODIGONAVIO IS 'CODIGO DE IDENTIFICAÃ‡ÃƒO DO NAVIO (PRIMARY KEY)';
COMMENT ON COLUMN CADNAVIO.QTDPORAO IS 'QUANTIDADE DE PORÃ•ES QUE O NAVIO POSSUI';
COMMENT ON COLUMN CADNAVIO.CODIGOPAISORIGEM IS 'PAÃS DE ORIGEM DO NAVIO';

/*
###########################################################################################################################################################
															CRIAÃ‡ÃƒO DA TABELA CADUSUARIO
###########################################################################################################################################################
*/

CREATE TABLE GRUPOUSUARIO (
	CODIGOGRUPO NUMBER(3) NOT NULL,
	DESCRICAO VARCHAR2(20) NOT NULL,
	PERMISSAO_INSERT_NAVIO CHAR(1) DEFAULT 'F',
	PERMISSAO_ALTER_NAVIO CHAR(1) DEFAULT 'F',
	PERMISSAO_CONSUL_NAVIO CHAR(1) DEFAULT 'F',
	PERMISSAO_DELET_NAVIO CHAR(1) DEFAULT 'F',
	PERMISSAO_INSERT_USER CHAR(1) DEFAULT 'F',
	PERMISSAO_ALTER_USER CHAR(1) DEFAULT 'F',
	PERMISSAO_CONSUL_USER CHAR(1) DEFAULT 'F',
	PERMISSAO_DELET_USER CHAR(1) DEFAULT 'F',
	PERMISSAO_INSERT_MOVIMENTO CHAR(1) DEFAULT 'F',
	PERMISSAO_ALTER_MOVIMENTO CHAR(1) DEFAULT 'F',
	PERMISSAO_CONSUL_MOVIMENTO CHAR(1) DEFAULT 'F',
	PERMISSAO_DELET_MOVIMENTO CHAR(1) DEFAULT 'F',
	PERMISSAO_INSERT_EMBARQUE CHAR(1) DEFAULT 'F',
	PERMISSAO_ALTER_EMBARQUE CHAR(1) DEFAULT 'F',
	PERMISSAO_CONSUL_EMBARQUE CHAR(1) DEFAULT 'F',
	PERMISSAO_DELET_EMBARQUE CHAR(1) DEFAULT 'F',
	
	CONSTRAINT PK_GRUPOUSUARIO PRIMARY KEY (CODIGOGRUPO),
	CONSTRAINT UN_GRUPOUSUARIO_DESCRICAO UNIQUE(DESCRICAO)
	
);
COMMENT ON TABLE GRUPOUSUARIO IS 'TABELA QUE DEFINE O NÃVEL DE PERMISSÃƒO DE CADA USUÃRIO';
COMMENT ON COLUMN GRUPOUSUARIO.PERMISSAO IS 'ADM - ADMINISTRADOR, DIR - DIRETOR,SUP - SUPERVISOR, OPR - OPERARIO';
CREATE SEQUENCE SEQ_CODIGO_GRUPOUSUARIO
	START WITH 1
	INCREMENT BY 1
	NOCYCLE
	NOCACHE
	;

CREATE OR REPLACE TRIGGER GRUPOUSUARIO_CODIGO_TIGGER
    BEFORE INSERT ON GRUPOUSUARIO FOR EACH ROW
  WHEN (NEW.CODIGOGRUPO IS NULL OR NEW.CODIGOGRUPO = 0)
  BEGIN
    SELECT SEQ_CODIGO_GRUPOUSUARIO.NEXTVAL INTO :NEW.CODIGOGRUPO FROM dual;
  END;

/*
###########################################################################################################################################################
															CRIAÃ‡ÃƒO DA TABELA CADUSUARIO
###########################################################################################################################################################
*/

CREATE TABLE CADUSUARIO (
	CODIGOUSUARIO NUMBER(3) NOT NULL,
	LOGIN VARCHAR2(10) NOT NULL,
	SENHA VARCHAR2(50) NOT NULL,
	CODIGOGRUPO NUMBER(3) NOT NULL,
	ALTERASENHA CHAR(1) DEFAULT 'F',
	
	CONSTRAINT PK_CADUSUARIO PRIMARY KEY (CODIGOUSUARIO),
	CONSTRAINT UN_CADUSUARIO_LOGIN UNIQUE(LOGIN),
	CONSTRAINT FK_CADUSUARIO_GRUPOUSUARIO FOREIGN KEY(CODIGOGRUPO) REFERENCES GRUPOUSUARIO(CODIGOGRUPO)
);

CREATE SEQUENCE SEQ_CODIGO_CADUSUARIO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE
    ; 
	
CREATE OR REPLACE TRIGGER SEQ_CODIGO_CADUSUARIO
    BEFORE INSERT ON CADUSUARIO FOR EACH ROW
  WHEN (NEW.CODIGOUSUARIO IS NULL OR NEW.CODIGOUSUARIO = 0)
  BEGIN
    SELECT SEQ_CODIGO_CADUSUARIO.NEXTVAL INTO :NEW.CODIGOUSUARIO FROM dual;
  END;
/*
###########################################################################################################################################################
															CRIAÃ‡ÃƒO DA TABELA EMBARQUE
###########################################################################################################################################################
*/


CREATE TABLE EMBARQUE (
    CODIGOEMBARQUE NUMBER(7) NOT NULL,
	PERIODOSAFRA NUMBER
	CODIGOUSUARIO NUMBER(3) NOT NULL,
    CODIGONAVIO NUMBER(7) NOT NULL,
    CODIGOPAISDESTINO NUMBER(3) NOT NULL,
    QTDAEMBARCAR NUMBER(9,2) NOT NULL,
	STATUS CHAR(1) DEFAULT 'N' NOT NULL,
	CODIGOSAFRA NUMBER(7),
	DATAINCLUSAO DATE NOT NULL,
	DATAFINAL DATE,
	TOTALEMBARCADO NUMBER(9,3),
	CANCELADO CHAR(1) DEFAULT 'F' NOT NULL,
	
	
    CONSTRAINT PK_EMBARQUE PRIMARY KEY(CODIGOEMBARQUE),
	CONSTRAINT FK_EMBARQUE_CADUSUARIO FOREIGN KEY (CODIGOUSUARIO) REFERENCES CADUSUARIO(CODIGOUSUARIO),
	CONSTRAINT FK_CADNAVIO_CADNAVIO FOREIGN KEY (CODIGONAVIO) REFERENCES CADNAVIO(CODIGONAVIO),
    CONSTRAINT FK_CADPAIS_CADPAIS FOREIGN KEY (CODIGOPAISDESTINO) REFERENCES CADPAIS(CODIGOPAIS),
	CONSTRAINT FK_EMBARQUE_CADSAFRA FOREIGN KEY (CODIGOSAFRA) REFERENCES CADSAFRA(CODIGO),
	CONSTRAINT CK_EMBARQUE_STATUS CHECK(STATUS IN ('N','A','P','F')),
    CONSTRAINT CK_EMBARQUE_CANCELADO CHECK(CANCELADO IN('T','F'))
);
CREATE SEQUENCE SEQ_CODIGO_EMBARQUE
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE
	;

CREATE OR REPLACE TRIGGER SEQ_CODIGO_EMBARQUE
    BEFORE INSERT ON EMBARQUE FOR EACH ROW
  WHEN (NEW.CODIGOEMBARQUE IS NULL OR NEW.CODIGOEMBARQUE = 0)
  BEGIN
    SELECT SEQ_CODIGO_EMBARQUE.NEXTVAL INTO :NEW.CODIGOEMBARQUE FROM dual;
  END;
COMMENT ON TABLE EMBARQUE IS 'TABELA PRINCIPAL DO SISTEMA, ONDE SÃO REGISTRADOS TODOS OS EMBARQUES';
COMMENT ON COLUMN EMBARQUE.STATUS IS 'A - EM ANDAMENTO, P - PAUSADO, F - FINALIZADO, C - CANCELADO';


CREATE TABLE MOVIMENTOEMBARQUE (
	CODIGOMOVIMENTOEMBARQUE NUMBER(10) NOT NULL,
	CODIGOEMBARQUE NUMBER(7) NOT NULL,
	CODIGOUSUARIO NUMBER(7) NOT NULL,
	CODIGOPAUSA NUMBER(7),
	DATAMOVIMENTO DATE NOT NULL,
	COMENTARIOPAUSA VARCHAR2(120),
	CANCELADO CHAR(1) DEFAULT 'F' NOT NULL,
	TIPOMOVIMENTO CHAR(1) NOT NULL,
	
	CONSTRAINT PK_MOVIMENTOEMBARQUE PRIMARY KEY (CODIGOMOVIMENTOEMBARQUE, PAUSA),
	CONSTRAINT FK_MOVIMENTOEMBARQUE_EMBARQUE FOREIGN KEY (CODIGOEMBARQUE) REFERENCES EMBARQUE (CODIGOEMBARQUE),
	CONSTRAINT FK_MOVIMENTOEMBARQUE_CADUSUARIO FOREIGN KEY (CODIGOUSUARIO) REFERENCES CADUSUARIO (CODIGOUSUARIO),
	CONSTRAINT FK_MOVIMENTOEMBARQUE_CODIGOPAUSA FOREIGN KEY (PAUSA) REFERENCES CADPAUSA(CODIGOPAUSA),
	CONSTRAINT CK_EMBARQUE_STATUS CHECK(STATUS IN ('I','P','F','R'))
);

COMMENT ON TABLE MOVIMENTOEMBARQUE IS 'TABELA QUE IRÁ CONTER TODA MOVIMENTAÇÃO DOS EMBARQUES';
COMMENT ON COLUMN MOVIMENTOEMBARQUE.CODIGOEMBARQUE IS 'INDICA A QUAL EMBARQUE ESSE MOVIMENTO PERTENCE';
COMMENT ON COLUMN MOVIMENTOEMBARQUE.CODIGOUSUARIO IS 'INDICA QUAL USUÁRIO EFETUOU A MOVIMENTAÇÃO';
COMMENT ON COLUMN MOVIMENTOEMBARQUE.STATUS IS 'I - INICIADO, P - PAUSADO, R - REINICIADO - F FINALIZADO';

CREATE SEQUENCE SEQ_CODIGO_MOVIMENTOEMBARQUE
	START WITH 1
	INCREMENT BY 1
	NOCYCLE
	NOCACHE
	;
CREATE TABLE CADPAUSA(
    CODIGOPAUSA NUMBER(7),
    DESCRICAO VARCHAR2(50),

    CONSTRAINT PK_PAUSA PRIMARY KEY (CODIGOPAUSA),
    CONSTRAINT UN_PAUSA_DESCRICAO UNIQUE (DESCRICAO)
);
CREATE SEQUENCE SEQ_CODIGO_CADPAUSA
	START WITH 1
	INCREMENT BY 1
	NOCYCLE
	NOCACHE
	;
/*
###########################################################################################################################################################
															CRIAÃ‡ÃƒO DA TABELA SAFRA
###########################################################################################################################################################
*/
CREATE TABLE CADSAFRA(
	CODIGOSAFRA NUMBER(7),
	PERIODOSAFRA VARCHAR2(10) NOT NULL,
	ORDEM NUMBER(7),

	CONSTRAINT PK_SAFRA PRIMARY KEY (CODIGO),
	CONSTRAINT UN_SAFRA_PERIODOSAFRA UNIQUE (PERIODOSAFRA)
);
CREATE SEQUENCE SEQ_CODIGO_SAFRA
	START WITH 1
	INCREMENT BY 1
	NOCYCLE
	NOCACHE
	;
--VERIFICAR
/*
CREATE TABLE LOG_ACAO
(	
	TABLE_NAME VARCHAR2(30) NOT NULL,
	CODIGO_USUARIO NUMBER,
	timestamp date,
	ACAO CHAR(1) NOT NULL CHECK (ACAO IN ('I','D','U')),
	INF_ANTERIOR VARCHAR2(30),
	INF_ATUAL VARCHAR2(30),
	QUERY VARCHAR2(100)
)
----------------------------------------------------------
CREATE TABLE LOG_ACAO
(	
	TABLE_NAME VARCHAR2(30) NOT NULL,
	CODIGO_USUARIO NUMBER,
	timestamp date,
	ACAO CHAR(1) NOT NULL CHECK (ACAO IN ('I','D','U')),
	INF_ANTERIOR VARCHAR2(30),
	INF_ATUAL VARCHAR2(30),
	QUERY VARCHAR2(100)
)

CREATE OR REPLACE TRIGGER CADNAVIO_LOG_ACAO

   AFTER INSERT OR UPDATE OR DELETE ON CADNAVIO

     FOR EACH ROW

 DECLARE


   ACAO LOG_ACAO.ACAO%TYPE;

 BEGIN

   IF INSERTING THEN 


      ACAO := 'I';

   ELSIF DELETING THEN

     ACAO := 'D';


   ELSIF UPDATING THEN


    ACAO := 'U';

   END IF;

 


INSERT INTO LOG_ACAO
(	
	TABLE_NAME,
	CODIGO_USUARIO,
	timestamp,
	ACAO,
	INF_ANTERIOR,
	INF_ATUAL,
	QUERY
)VALUES
(
	'CADNAVIO',
	CODIGONAVIO,
	SYSDATE,
	ACAO,
	:OLD.DESCRICAO,
    :NEW.DESCRICAO,
	'FALTA COLOCAR COMANDO SQL'
);

END;
*/	